# Generated by Django 4.0.3 on 2022-05-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='isCompleted',
            new_name='completed',
        ),
    ]
