# Generated by Django 4.0.3 on 2022-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_iscompleted_todomodel_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
